# Generated by Django 5.0.2 on 2024-07-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='price',
        ),
    ]
